name: sphinx-doc

on:
  push:
    branches:    
    - main
    paths:
    - src/docs/**

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and commit doc changes
    # Publish built docs to gh-pages branch.
    # ===============================
      run: |
        mkdir src/docs/_build && mkdir src/docs/_static &&  chmod gou+wrx -R src/docs
        docker run -v $(pwd):/datos --entrypoint /bin/bash --rm palmoreck/jupyterlab_optimizacion_2:3.0.0 -c "export PATH=$PATH:/home/miuser/.local/bin/ && cd /datos/src && pip install sphinx-rtd-theme && cd ../src/docs && make html"
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/docs/_build/html/
