name: test own maxflow function
on: 
  push:
   branches:
    - main
   paths:
    - test_maxflowaeiu.py

jobs:
  build:
    name: Autograding Test max flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalar dependencias de Python para el Test
        run: |
          python -m pip install --upgrade pip
          pip install pandas flake8 pytest networkx scipy MaxFlowAeiu==0.1.2
          
      - name: Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Ejecutar pytest
        run: pytest test_maxflowaeiu.py